FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD: user1234
ENV MYSQL_DATABASE: traveldb
ENV MYSQL_USER: user
ENV MYSQL_PASSWORD: user1234

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]